### ISSUE TITLE
Example build fails

### ISSUE THREAD

**Issue by Eugeny** [endlessm/electron-installer-flatpak#5]
**What version of `electron-installer-flatpak` are you using?**
0.4.1

**What version of `node` and `npm` are you using?**
7.3.0 / 3.10.10

**What operating system are you using?**
Ubuntu Xenial x64

**Can you compile the [example app](https://github.com/endlessm/electron-installer-flatpak/tree/master/example) successfully?**
No

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/endlessm/electron-installer-flatpak.git
$ cd electron-installer-flatpak/example
$ DEBUG='electron-installer-flatpak' npm run build
```

```

> poopie@0.0.1 build /home/eugene/Work/electron-installer-flatpak/example
> npm run clean && npm run exe32 && npm run flatpak32 && npm run exe64 && npm run flatpak64


> poopie@0.0.1 clean /home/eugene/Work/electron-installer-flatpak/example
> rimraf dist


> poopie@0.0.1 exe32 /home/eugene/Work/electron-installer-flatpak/example
> electron-packager . poopie --platform linux --arch ia32 --out dist/ --ignore "(dist|node_modules/electron.*)"

Packaging app for platform linux ia32 using electron v1.4.13
Wrote new app to dist/poopie-linux-ia32

> poopie@0.0.1 flatpak32 /home/eugene/Work/electron-installer-flatpak/example
> electron-installer-flatpak --src dist/poopie-linux-ia32/ --arch ia32 --config config.json

Creating package (this may take a while)
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Reading package metadata from dist/poopie-linux-ia32/resources/app/package.json
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating package with options
{
  "src": "dist/poopie-linux-ia32/",
  "arch": "ia32",
  "config": "config.json",
  "dest": "dist/installers/",
  "icon": "resources/Icon.png",
  "categories": [
    "Utility"
  ],
  "depends": [
    "git",
    "gconf2",
    "gconf-service",
    "gvfs-bin",
    "libc6",
    "libcap2",
    "libgtk2.0-0",
    "libudev0 | libudev1",
    "libgcrypt11 | libgcrypt20",
    "libappindicator1",
    "libnotify4",
    "libnss3",
    "libxtst6",
    "python",
    "xdg-utils"
  ],
  "lintianOverrides": [
    "changelog-file-missing-in-native-package"
  ],
  "id": "io.atom.electron.poopie",
  "productName": "poopie",
  "genericName": "poopie",
  "description": "An example app, built with Electron.",
  "branch": "master",
  "base": "io.atom.electron.BaseApp",
  "baseVersion": "master",
  "baseFlatpakref": "https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref",
  "runtime": "org.freedesktop.Platform",
  "runtimeVersion": "1.4",
  "sdk": "org.freedesktop.Sdk",
  "finishArgs": [
    "--socket=x11",
    "--share=ipc",
    "--device=dri",
    "--socket=pulseaudio",
    "--filesystem=home",
    "--filesystem=/tmp",
    "--share=network",
    "--talk-name=org.freedesktop.Notifications"
  ],
  "bin": "poopie",
  "mimeType": []
}
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating temporary directory
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating contents of package
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating desktop file at /tmp/electron-1161130-20328-1bnkic0.csdbc323xr/io.atom.electron.poopie_undefined_ia32/share/applications/io.atom.electron.poopie.desktop
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Generating template from /home/eugene/Work/electron-installer-flatpak/example/node_modules/electron-installer-flatpak/resources/desktop.ejs
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating icon file at /tmp/electron-1161130-20328-1bnkic0.csdbc323xr/io.atom.electron.poopie_undefined_ia32/share/pixmaps/io.atom.electron.poopie.png
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating copyright file at /tmp/electron-1161130-20328-1bnkic0.csdbc323xr/io.atom.electron.poopie_undefined_ia32/share/doc/io.atom.electron.poopie/copyright
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Reading license file from dist/poopie-linux-ia32/LICENSE
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Copying application to /tmp/electron-1161130-20328-1bnkic0.csdbc323xr/io.atom.electron.poopie_undefined_ia32/lib/io.atom.electron.poopie
Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Generated template from /home/eugene/Work/electron-installer-flatpak/example/node_modules/electron-installer-flatpak/resources/desktop.ejs
[Desktop Entry]
Name=poopie
Comment=An example app, built with Electron.
GenericName=poopie
Exec=poopie %U
Icon=io.atom.electron.poopie
Type=Application
StartupNotify=true
Categories=Utility;


Fri, 30 Dec 2016 12:54:56 GMT electron-installer-flatpak Creating package at dist/installers/io.atom.electron.poopie_master_ia32.flatpak
Fri, 30 Dec 2016 12:55:27 GMT electron-installer-flatpak Error creating package: flatpak failed with status code 1
Error: flatpak failed with status code 1
    at ChildProcess.child.on (/home/eugene/Work/electron-installer-flatpak/example/node_modules/flatpak-bundler/index.js:74:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12) 'Error: flatpak failed with status code 1\n    at ChildProcess.child.on (/home/eugene/Work/electron-installer-flatpak/example/node_modules/flatpak-bundler/index.js:74:16)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:885:16)\n    at Socket.<anonymous> (internal/child_process.js:334:11)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at Pipe._handle.close [as _onclose] (net.js:501:12)'

npm ERR! Linux 4.8.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "flatpak32"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! poopie@0.0.1 flatpak32: `electron-installer-flatpak --src dist/poopie-linux-ia32/ --arch ia32 --config config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poopie@0.0.1 flatpak32 script 'electron-installer-flatpak --src dist/poopie-linux-ia32/ --arch ia32 --config config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poopie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-installer-flatpak --src dist/poopie-linux-ia32/ --arch ia32 --config config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poopie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poopie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eugene/Work/electron-installer-flatpak/example/npm-debug.log

npm ERR! Linux 4.8.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! poopie@0.0.1 build: `npm run clean && npm run exe32 && npm run flatpak32 && npm run exe64 && npm run flatpak64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poopie@0.0.1 build script 'npm run clean && npm run exe32 && npm run flatpak32 && npm run exe64 && npm run flatpak64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poopie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run exe32 && npm run flatpak32 && npm run exe64 && npm run flatpak64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poopie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poopie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eugene/Work/electron-installer-flatpak/example/npm-debug.log
```

Strace: https://gist.githubusercontent.com/Eugeny/087eb9d66b3aa9ac1c1b3c99eaf421bf/raw/be7c22721e63fd1430e547769f4eb64917c06713/strace.txt

**Comment by malept** [comment]
I think I'm getting the same problem. It specifically happens when I try to build a non-`x86_64` app. Try running `DEBUG='electron-installer-flatpak,flatpak-bundler' npm run build`. If it's the same as me, it'll look something like this (truncated output):

```
  flatpak-bundler $ flatpak info --show-commit --user io.atom.electron.BaseApp/i386/master +1ms
  flatpak-bundler $ flatpak info --show-commit --system io.atom.electron.BaseApp/i386/master +23ms
  flatpak-bundler 2> error: io.atom.electron.BaseApp master not installed
  flatpak-bundler  +29ms
  flatpak-bundler 2> error: io.atom.electron.BaseApp master not installed
  flatpak-bundler  +1ms
  flatpak-bundler No install of io.atom.electron.BaseApp found, trying to install from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref +1ms
  flatpak-bundler $ flatpak install --user --arch i386 --from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref +0ms
  flatpak-bundler 2> error: App io.atom.electron.BaseApp, branch master is already installed
  flatpak-bundler  +257ms
  electron-installer-flatpak Error creating package: flatpak failed with status code 1 +4ms
```

My guess is that this flatpak repo only has built `x86_64` for `io.atom.electron.BaseApp`?

**Comment by Eugeny** [comment]
@malept I'm getting the same, but also:
```

Sat, 31 Dec 2016 13:53:26 GMT flatpak-bundler 1> The required runtime org.freedesktop.Platform/x86_64/1.4 was not found in a configured remote.

Sat, 31 Dec 2016 13:53:26 GMT flatpak-bundler 2> error: The Application io.atom.electron.BaseApp/x86_64/master requires the runtime org.freedes
ktop.Platform/x86_64/1.4 which is not installed
```

**Comment by Eugeny** [comment]
And same if I remove the x32 build commands from package.json

```
Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler Checking for install of io.atom.electron.BaseApp                                         [48/475]
Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler $ flatpak info --show-commit --user io.atom.electron.BaseApp/x86_64/master
Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler $ flatpak info --show-commit --system io.atom.electron.BaseApp/x86_64/master
Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler 2> error: io.atom.electron.BaseApp master not installed

Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler 2> error: io.atom.electron.BaseApp master not installed

Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler No install of io.atom.electron.BaseApp found, trying to install from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref
Sat, 31 Dec 2016 13:56:45 GMT flatpak-bundler $ flatpak install --user --arch x86_64 --from https://s3-us-west-2.amazonaws.com/electron-flatpak
.endlessm.com/electron-base-app-master.flatpakref
Sat, 31 Dec 2016 13:56:48 GMT flatpak-bundler 1> Installing: io.atom.electron.BaseApp/x86_64/master

Sat, 31 Dec 2016 13:56:50 GMT flatpak-bundler 1> Required runtime for io.atom.electron.BaseApp/x86_64/master (org.freedesktop.Platform/x86_64/1
.4) is not installed, searching...

Sat, 31 Dec 2016 13:56:50 GMT flatpak-bundler 1> The required runtime org.freedesktop.Platform/x86_64/1.4 was not found in a configured remote.

Sat, 31 Dec 2016 13:56:50 GMT flatpak-bundler 2> error: The Application io.atom.electron.BaseApp/x86_64/master requires the runtime org.freedes
ktop.Platform/x86_64/1.4 which is not installed

Sat, 31 Dec 2016 13:56:50 GMT electron-installer-flatpak Error creating package: flatpak failed with status code 1
```

**Comment by malept** [comment]
@Eugeny my understanding is that you need to add the remote that contains the Freedesktop.org runtime first:

```bash
flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
```

**Comment by Eugeny** [comment]
Now it's found but electron-installer-flatpak doesn't auto-install it:

```
Sat, 31 Dec 2016 21:44:21 GMT flatpak-bundler 1> Required runtime for io.atom.electron.BaseApp/x86_64/master (org.freedesktop.Platform/x86_64/1
.4) is not installed, searching...

Sat, 31 Dec 2016 21:44:23 GMT flatpak-bundler 1> Found in remote gnome, do you want to install it? [y/n]: n
```

**Comment by malept** [comment]
Hmmm. Yeah, in [my app](https://github.com/malept/gmusicprocurator-app/pull/4/files#diff-cfd2b863eadb60a3df51a7240158dba1R8) I install the runtime before I build my flatpak (via [Electron Forge](https://github.com/electron-userland/electron-forge), which uses this module).

**Comment by Eugeny** [comment]
Worked after doing `flatpak install --user --arch x86_64 --from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref`, probably worth mentioning in the README?

**Comment by malept** [comment]
Weird. I didn't need to do that. I should point out that the CI for Electron Forge doesn't do that and creates a flatpak for x86_64 on each run.

**Comment by Eugeny** [comment]
That's the command from the debug log that required a manual "y" input but failed because `e-i-f` didn't do that.

**Comment by mattdangerw** [comment]
Thanks for filing! I think there might be a couple things going on here...

 * The code trying to autoinstall the base app will fail if the freedesktop runtimes are not installed. The runtimes aren't strictly needed for building the example app though, so I think there's a simple fix for `flatpak-bundler` to that. Another option could be to set up electron-installer-flatpak to autoinstall the freedesktop runtimes.
 * For compiling i386 app from x86_64, I think there's a bug in flatpak itself that's breaking installing for another arch from a flatpakref file https://github.com/flatpak/flatpak/issues/406. I'll try to look more into that one.

**Comment by malept** [comment]
@mattdangerw thanks, I appreciate you looking into these problems!

**Comment by mattdangerw** [comment]
Put up some small fixes
https://github.com/endlessm/electron-installer-flatpak/pull/6
https://github.com/endlessm/flatpak-bundler/pull/3

And a fix to flatpak for the problems install from a flatpakref for a specific arch.

**Comment by mattdangerw** [comment]
Fixes are in, building for multi-arch will still require some manual dependency installs which are detailed in the README.

The flatpak bug fix for properly handling arch and flatpakref files just merged to master as well. Once that makes its way into a flatpak release everything should go back to properly auto installing in the multi-arch case.

**Comment by mattdangerw** [comment]
Should be all fixed up now, with flatpak > 0.8.2. Closing the issue.

Any more problems here let me know.

**Comment by mattdangerw** [comment]
Should be all fixed up now, with flatpak > 0.8.2. Closing the issue.

Any more problems here let me know.

**Comment by LoLei** [comment]
I'm still getting them same though, what @Eugeny said (https://github.com/endlessm/electron-installer-flatpak/issues/5#issuecomment-269866043).

```
flatpak-bundler $ flatpak info --show-commit --system org.freedesktop.Platform/x86_64/1.4 +5ms
  flatpak-bundler 2> error: org.freedesktop.Platform/x86_64/1.4 not installed
  flatpak-bundler  +13ms
  flatpak-bundler 2> error: org.freedesktop.Platform/x86_64/1.4 not installed
  flatpak-bundler  +4ms
  flatpak-bundler No install of org.freedesktop.Platform found, trying to install from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref +1ms
  flatpak-bundler $ flatpak install --user --no-deps --arch x86_64 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref +0ms
  flatpak-bundler 2> error: No such ref 'runtime/org.freedesktop.Platform/x86_64/1.4' in remote platform-origin
```

What could possibly be the reason this does not work:
https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref
Has the entry: `Url=http://sdk.gnome.org/repo/`.
However, the `sdk.gnome.org` URLs do no longer exist, they have been switched to `nightly`. [[1](https://www.reddit.com/r/gnome/comments/dut47k/what_happened_to_sdkgnomeorg_flatpak_repos/)].

@mattdangerw Could you change [`flatpak-bundler`](https://github.com/endlessm/flatpak-bundler) to reflect the URL changes?

**Comment by malept** [comment]
While we're waiting for a fix in the main repository, I've been [maintaining a fork](https://github.com/malept/electron-installer-flatpak) (which I am happy to contribute changes back here) that fixes such problems.
